version: '2'

services:
  stocks:
    build: .
    ports:
      - '4001:3000'
    container_name: stocks
    volumes:
      - .:/usr/src/app
    environment:
      - MYSQL_HOST=ilada-mysql.cmspp4j0ajle.ap-southeast-2.rds.amazonaws.com
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=Ekk1120300068864ilada
      - MYSQL_DATABASE=stocks
